config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  get 'top/main' 
  resources :products 
  resources :cart_items, only: [:new, :create, :destroy] 
  resources :carts, only: [:show] 
end 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :cart_items
  has_many :products, through: :cart_items
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :product
  belongs_to :cart
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :cart_items
  has_many :carts, through: :cart_items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # current_cartをヘルパーメソッドとして利用可能にする
  helper_method :current_cart

  private

  # セッションにカートのIDがあればそのカートを、なければ新しいカートを返す
  def current_cart
    if session[:cart_id]
      @current_cart ||= Cart.find(session[:cart_id])
    else
      @current_cart = Cart.create
      session[:cart_id] = @current_cart.id
    end
    @current_cart
  end
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  def new
    @cart_item = CartItem.new(product_id: params[:product_id])
  end

  def create
    @cart_item = CartItem.new(cart_item_params)
    if @cart_item.save
      redirect_to products_path
    else
      render :new
    end 
  end

  def destroy 
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy 
    redirect_to cart_path(@cart_item.cart_id)
  end 

  private 

  def cart_item_params 
    params.require(:cart_item).permit(:qty, :product_id, :cart_id)
  end 
end 

app/controllers/carts_controller.rb
class CartsController < ApplicationController 
  def show 
    @cart = Cart.find(params[:id])
  end 
end 

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_path
    else
      render :new
    end
  end

  def destroy
    @product = Product.find(params[:id])
    @product.destroy
    redirect_to products_path
  end

  private

  def product_params
    params.require(:product).permit(:name, :price)
  end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
    def main
        render 'top/main'
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/cart_items/new.html.erb
<h1>商品をカートに追加</h1>
<%= form_with model: @cart_item, local: true do |f| %>
  <div>
    <%= f.label :qty, "数量" %>
    <%= f.number_field :qty %>
  </div>
  <div>
    <%= f.hidden_field :product_id %>
    <%= f.hidden_field :cart_id, value: Cart.first_or_create.id %>
  </div>
  <div>
    <%= f.submit 'カートに追加' %>
  </div>
<% end %>

app/views/carts/show.html.erb
<h1>カート</h1>
<table>
  <tr>
    <th>商品</th>
    <th>価格</th>
    <th>数量</th>
    <th>値段</th>
    <th></th>
  </tr>
  <% @cart.cart_items.each do |cart_item| %>
  <tr>
    <td><%= cart_item.product.name %></td>
    <td><%= cart_item.product.price %></td>
    <td><%= cart_item.qty %></td>
    <td><%= cart_item.product.price * cart_item.qty %></td>
    <td><%= link_to '削除', cart_item, method: :delete, data: { confirm: '本当に削除しますか?' } %></td>
  </tr>
  <% end %>
</table>
<%= link_to '商品一覧',  products_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>L6</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<h1>商品一覧</h1>
<ul>
<% @products.each do |p| %>
  <li>
    <%= p.name %>
    <%= p.price %>円
    <%= link_to 'カート追加', new_cart_item_path(product_id: p.id)%>
    <%= button_to '削除', product_path(p), method: :delete, data: { confirm: '本当に削除しますか？' } %>
  </li>
<% end %>
<%= link_to '商品を追加する', new_product_path %>
<%= link_to 'カートを見る', cart_path(current_cart.id) %>

</ul>

app/views/products/new.html.erb
<h1>新しい商品を登録</h1>
<%= form_with model: @product, url: products_path do |f| %>
  <div>
    <%= f.label :name, '商品名'%>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :price, '価格' %>
    <%= f.number_field :price %>
  </div>
  <div>
    <%= f.submit '作成' %>
  </div>
<% end %>